### ISSUE TITLE
module.js:14 syntax error

### ISSUE THREAD

**Issue by mehimself** [nuxt-community/express-template#101]
/Users/mrec/Desktop/edo/node_modules/nuxt/lib/core/module.js:14
  async ready() {
             ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mrec/Desktop/edo/node_modules/nuxt/lib/core/index.js:2:16)
    at Module._compile (module.js:570:32)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c80">#c80</a>)</em></sub></div>

**Comment by FrancisBou** [comment]
I am experiencing the same issue on Windows, works fine on Ubuntu. Not sure if this is related.

**Comment by aungyin** [comment]
same issue on mac. 
npm version: 5.3.0
vue-cli: 2.7.0
