### ISSUE TITLE
The project cannot be started

### ISSUE THREAD

**Issue by wangweiji1006** [nuxt-community/express-template#212]
hello,when running the program:
1.npm run dev
> nuxt-express@1.0.0 dev
> nuxt

Nuxi 3.0.0                                                                                                                                                                                                 11:00:59  
Usage: npx nuxi dev|build|build-module|cleanup|clean|preview|start|analyze|generate|prepare|typecheck|usage|info|init|create|upgrade|test|add|new [args]                                                   11:00:59  

Use npx nuxi [command] --help to see help for each command 
2.when run "npx nuxi dev":
Nuxi 3.0.0                                                                                                                                                                                                 
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                                                                                
 ERROR  Cannot read properties of undefined (reading 'options')                                                                                                                                           
  at httpModule (node_modules\@nuxt\http\lib\module.js:10:35)
  at installModule (/C:/Users/Administrator/Downloads/Compressed/express-template-master_2/express-template-master/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (/C:/Users/Administrator/Downloads/Compressed/express-template-master_2/express-template-master/node_modules/nuxt/dist/index.mjs:1825:7)
  at async loadNuxt (/C:/Users/Administrator/Downloads/Compressed/express-template-master_2/express-template-master/node_modules/nuxt/dist/index.mjs:1857:5)
  at async loadNuxt (/C:/Users/Administrator/Downloads/Compressed/express-template-master_2/express-template-master/node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async Object.invoke (/C:/Users/Administrator/Downloads/Compressed/express-template-master_2/express-template-master/node_modules/nuxi/dist/chunks/build.mjs:34:18)
  at async _main (/C:/Users/Administrator/Downloads/Compressed/express-template-master_2/express-template-master/node_modules/nuxi/dist/cli.mjs:50:20)

====ps.====
node -v
v16.15.0
npm -v
9.2.0

**Comment by Explosion-Scratch** [comment]
Happening for me as well

**Comment by Explosion-Scratch** [comment]
Screenshot with basic start:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/61319150/216832394-35412f21-3569-46a9-a654-806822fa3ebe.png">

**Comment by Cynthia1911** [comment]
I changed nuxt version to '2' and project started

**Comment by Bayn-Web** [comment]
this problem is solved by lock nuxt version to ^2. Thinking the author made the project to early but the nuxt version in package.json is still keep latest.
