### ISSUE TITLE
Crash with Vuetify

### ISSUE THREAD

**Issue by guumaster** [nuxt-community/express-template#30]
Before adding `backpack` this template worked ok with Vuetify. But now it crash when it tries to load `*.styl` files. When I run  `npm run dev` throws this is the error: 

```
* !!vue-style-loader!css-loader!../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-216ea150","scoped":false,"hasInlineConfig":true}!stylus-loader!css/app.styl in ./.nuxt/App.vue

To install it, you can run: npm install --save !!vue-style-loader!css-loader!../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-216ea150","scoped":false,"hasInlineConfig":true}!stylus-loader!css/app.styl

``` 

This is part of my `nuxt.config.js` that worked previously:

```js
  //...
  plugins: ['~plugins/vuetify.js'],
  css: [
    {src: join(__dirname, 'css/app.styl'), lang: 'styl'}
  ],
  build: {
    vendor: ['vuetify', 'axios'],
  //....
```

I'm not sure how to fix it. Does `backpack` need the `vue-loader` config? Which part of the config should be updated?

**Comment by zb0t** [comment]
Do you have `stylus` and `stylus-loader` installed?

**Comment by guumaster** [comment]
I do, it works with the previous version of this template. It started failing after the addition of `backpack` dependency.

**Comment by zb0t** [comment]
I just pulled the template for a new project and it seems to work for me with Vuetify installed. Can you post your package.json?

**Comment by guumaster** [comment]
Its [here](https://github.com/guumaster/roleando-server/blob/master/package.json).

**Comment by guumaster** [comment]
I tried this: 

- `vue init nuxt/express  test`
- modified similarly to nuxt/examples/with-vuetify`
  - added folder `css` 
  - edit `nuxt.config.js` to add vuetify plugin and css load
  - installed `stylus` and `stylus-loader`

When I run `npm run dev` I get this error:
```
This dependency was not found:

* !!vue-style-loader!css-loader!../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-3f416696","scoped":false,"hasInlineConfig":true}!stylus-loader!css/app.styl in ./.nuxt/App.vue

To install it, you can run: npm install --save !!vue-style-loader!css-loader!../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-3f416696","scoped":false,"hasInlineConfig":true}!stylus-loader!css/app.styl
```

**Comment by guumaster** [comment]
@zb0t can you tell how did you make it work with vuetify? did you started with this template? what did you do next?

**Comment by barrongineer** [comment]
I get the same thing.

**Comment by fortil** [comment]
I had to install the previous version of Nuxt, with the new version i have many problems.

**Comment by fortil** [comment]
I share my problems:

I install the example like as you say in the README.md
Next, install `vuetify`, `stylus` and `stylus-loader`

This is my `nuxt.config.js` and my `plugin/vuetify.js`, too you show the folder list of the proyect
![image](https://cloud.githubusercontent.com/assets/6068654/26405399/c5932b84-405a-11e7-94d4-a4eb5da64880.png)

All is good until run `npm run dev`, all is crashed, xD
![image](https://cloud.githubusercontent.com/assets/6068654/26405474/050e442e-405b-11e7-8e46-9067667d8d4e.png)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle example-express@1.0.0~predev: example-express@1.0.0
6 silly lifecycle example-express@1.0.0~predev: no script for predev, continuing
7 info lifecycle example-express@1.0.0~dev: example-express@1.0.0
8 verbose lifecycle example-express@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle example-express@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\user\Documents\org\NC\example-express\node_modules\.bin;C:\Program Files (x86)\OpenSSH\bin;C:\Program Files\nodejs\;C:\Users\user\AppData\Roaming\npm;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\Composer\vendor\bin;C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;"C:\Program Files\nodejs";C:\Users\user\AppData\Roaming\npm
10 verbose lifecycle example-express@1.0.0~dev: CWD: C:\Users\user\Documents\org\NC\example-express
11 silly lifecycle example-express@1.0.0~dev: Args: [ '/d /s /c', 'backpack dev' ]
12 silly lifecycle example-express@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle example-express@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: example-express@1.0.0 dev: `backpack dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid example-express@1.0.0
16 verbose cwd C:\Users\user\Documents\org\NC\example-express
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error example-express@1.0.0 dev: `backpack dev`
22 error Exit status 1
23 error Failed at the example-express@1.0.0 dev script 'backpack dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the example-express package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     backpack dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs example-express
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls example-express
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Thanks.

**Comment by pi0** [comment]
This Issue (hopefully) should be fixed in next release thanks to @egoist PR. BTW can you please provide link to your git repo to reproduce this error?

**Comment by guumaster** [comment]
In my case the repo is this: https://github.com/guumaster/roleando-server

I haven't updated yet
