### ISSUE TITLE
backpack dev start faild

### ISSUE THREAD

**Issue by andysay** [nuxt-community/express-template#80]
> backpack dev

internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
    at spawn (/Users/andreyleonov/Desktop/news-ex/node_modules/cross-spawn/index.js:17:18)
    at startProcess (/Users/andreyleonov/Desktop/news-ex/node_modules/backpack-core/bin/backpack:44:16)
    at Object.<anonymous> (/Users/andreyleonov/Desktop/news-ex/node_modules/backpack-core/bin/backpack:53:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c61">#c61</a>)</em></sub></div>

**Comment by cannap** [comment]
try to run the cmd as admin

**Comment by syrex88** [comment]
I got other error, if I start in console command 'backpack dev' , but if start command backpack build  - error not found.
Code error:
> backpack dev

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by cannap** [comment]
can you try to add backpack to scripts in package.json
and use something like dev: "backpack dev"

**Comment by Prozi** [comment]
npm run backpack dev or have it in scripts

backpack dev runs global backpack

npm run backpack dev / package.json script runs from ./node_modules/.bin/...
