### ISSUE TITLE
npm run dev doesn't work

### ISSUE THREAD

**Issue by se7en-1992** [nuxt-community/express-template#97]
......./node_modules/nuxt/lib/core/module.js:14
  async ready() {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/se7en/Desktop/n2ex/node_modules/nuxt/lib/core/index.js:2:16)
    at Module._compile (module.js:570:32)

**Comment by se7en-1992** [comment]
i have Solved

**Comment by mehimself** [comment]
I have the same issue. How did you solve it?

**Comment by se7en-1992** [comment]
@mehimself use node 8.0.0+
